### ISSUE TITLE
phantom_evaluator: Unable to open file '/path/to/present working directory'

### ISSUE THREAD

**Issue by ckundo** [quailjs/quail-cli#6]
When I run `$ quail eval http://placekitten.com`, I expect to see evaluation results, but instead I get an error:

```
phantom_evaluator: Unable to open file '</path/to/present working directory>'
```

**Comment by kahunacohen** [comment]
HI any word on this? When I do the same I get: 

```
$ ./bin/quail eval http://www.google.com
WORKING_DIR/node_modules/.bin/phantomjs WORKING_DIR/src/js/scripts/phantom_evaluator.js  WORKING_DIR/home/cohenaa/projects/quail/config/config.json 
Unable to open file 'undefined'
```

I followed build instructions as per the README.

**Comment by alefort** [comment]
I'm also getting the same errors as kahunacohen.

**Comment by WilcoFiers** [comment]
Hey guys,
[QuailJS is no longer being maintained](https://github.com/quailjs/quail-core#deprecation), and neither is PhantomJS for that matter. I recommend you looking for alternatives. As a possible alternative I would suggest [axe-cli](https://github.com/dequelabs/axe-cli), which I am one of the developers of. There are other options out there too. The W3C maintains a list of different accessibility tools out there:

https://www.w3.org/WAI/ER/tools/

**Comment by alefort** [comment]
Thanks for the update, I hadn't noticed it was deprecated. I'll focus on using aXe-cli.

**Comment by kahunacohen** [comment]
@WilcoFiers can you tell me if axe-cli allows you to write your own custom tests?

**Comment by WilcoFiers** [comment]
@kahunacohen Currently not. There's a problem with the `--axe-source` flag. Once that's fixed you can load in a custom build of axe-core. What are some of the things you are missing? I'd recommend looking at contributing to axe-core if you're looking to expand the existing ruleset. There's some information about this here: https://github.com/dequelabs/axe-core/blob/develop/doc/rule-proposal.md
